# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ReactNativeStarter' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNSweetAlert', :path => '../node_modules/react-native-sweet-alert'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'RNInAppBrowser', :path => '../node_modules/react-native-inappbrowser-reborn'

  target 'ReactNativeStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_native_modules!
end

target 'ReactNativeStarter-tvOS' do
  target 'ReactNativeStarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
